name: CI-CD Homologation

on:
  pull_request:
    types: [opened, synchronize, edited, labeled]

jobs:
  check-homolog:
    runs-on: ubuntu-latest
    outputs:
      homolog: ${{ steps.set-homolog.outputs.homolog }}
    steps:
      - name: Verificar checkbox de homologação
        id: set-homolog
        run: |
          if echo "${{ github.event.pull_request.body }}" | grep -iq "\- \[x\] Enviar para homologação?"; then
            echo "homolog=true" >> $GITHUB_OUTPUT
          else
            echo "homolog=false" >> $GITHUB_OUTPUT
          fi

  detect-changes:
    needs: check-homolog
    if: ${{ needs.check-homolog.outputs.homolog == 'true' }}
    runs-on: ubuntu-latest
    outputs:
      run-client: ${{ steps.check.outputs.run_client }}
      run-api: ${{ steps.check.outputs.run_api }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Detectar mudanças
        id: check
        run: |
          CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }}...${{ github.head_ref }})
          echo "Arquivos alterados:"
          echo "$CHANGED_FILES"

          set_output() {
            local name=$1
            local pattern=$2
            if echo "$CHANGED_FILES" | grep -qE "$pattern"; then
              echo "$name=true" >> $GITHUB_OUTPUT
            else
              echo "$name=false" >> $GITHUB_OUTPUT
            fi
          }

          set_output "run-client" "^packages/apps/client/"
          set_output "run-api" "^packages/apps/api/"

  validate-client:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.run-client == 'true' }}
    uses: ./.github/workflows/ci-cd.client.yml

  validate-api:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.run-api == 'true' }}
    uses: ./.github/workflows/ci-cd.api.yml

  publish-homolog:
    needs: [validate-client, validate-api]
    if: ${{ needs.check-homolog.outputs.homolog == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configurar Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
      - name: Rebase na master
        run: |
          git fetch origin master
          git checkout ${{ github.head_ref }}
          git rebase origin/master
      - name: Push para a branch PR
        run: |
          git push origin ${{ github.head_ref }} --force-with-lease
      - name: Publicar em homolog
        run: |
          git checkout master
          git pull origin master
          git branch -D homolog || true
          git checkout -b homolog
          git cherry-pick origin/${{ github.head_ref }}
          git push origin homolog -f
