name: Build Homologation

on:
  pull_request:
    types: [opened, synchronize, edited, labeled]

jobs:
  build-homolog:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout do código
          uses: actions/checkout@v3