name: Build Homologation

on:
  pull_request:
    types: [opened, synchronize, edited, labeled]

jobs:
  check-homolog:
    runs-on: ubuntu-latest
    outputs:
      homolog: ${{ steps.set-homolog.outputs.homolog }}
    steps:
      - name: Verificar checkbox de homologação
        id: set-homolog
        run: |
          if echo "${{ github.event.pull_request.body }}" | grep -iq "\- \[x\] Enviar para homologação?"; then
            echo "homolog=true" >> $GITHUB_OUTPUT
          else
            echo "homolog=false" >> $GITHUB_OUTPUT
          fi
  validate-client:
    needs: check-homolog
    if: ${{ needs.check-homolog.outputs.homolog == 'true' && contains(github.event.pull_request.labels.*.name, '@flux/client') }}
    uses: ./.github/workflows/validate-client.yml

  validate-api:
    needs: check-homolog
    if: ${{ needs.check-homolog.outputs.homolog == 'true' && contains(github.event.pull_request.labels.*.name, '@flux/api') }}
    uses: ./.github/workflows/validate-api.yml

  final-step:
    needs: [validate-client, validate-api]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Todos os workflows passaram, podemos prosseguir!"